### ISSUE TITLE
Custom Path

### ISSUE THREAD

**Issue by AlbertoFdzM** [talecrafter/AnimationImporter#1]
Implement options to set custom paths for Sprites, Animations and Animation Controller exports.

**Comment by talecrafter** [comment]
What's your intended use case here? Do you need them as a general project setting or do you need custom paths per asset? Because I'm not sure how to handle the latter one, where to save that info, database or a custom asset with import settings per ase file. And are those paths relative to the asset or relative to project folder?

**Comment by AlbertoFdzM** [comment]
Just to organice the imports by type.

So for example defining something like `Animations/` in a text fields named `animation controllers folder` and `animations folder` and end up with something like this:
- my-pryect/
  - Library/
  - Assets/
    - Animations/
      - Player.anim
      - Player.controller
    - Sprites/
      - Player.ase
      - Player.png

It would be nice to have `Sprites Folder`, `AnimationControllers Folder` and `Animations Folder` to configure and organice the project files.

**Comment by talecrafter** [comment]
Ok. This seems useful. Right now though the Editor display gets a bit confusing, so the user doesn't know if the paths or subfolders are used and which one has preference. Ideally we would probably want three options for AnimatorController, Animations and Sprites individually:
- same folder
- relative path to Aseprite File
- global path (meaning relative to Project Folder)

I think we'll first figure out where to save project settings and then I'll take parts of your patch and give those three options. (Don't know how this is usually done but I leave the Pull Request open as a reminder.)

**Comment by AlbertoFdzM** [comment]
Awesome! Thanks to care about it.

**Comment by talecrafter** [comment]
Added functionality for this in a8bb0a0c9cc59571a2d953a4cf9d1ed45cdb5880.
