### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by edwardrowe** [talecrafter/AnimationImporter#11]
Our main character file is pretty darn big. For longer imports, it would be nice to show a progress bar.

http://docs.unity3d.com/ScriptReference/EditorUtility.DisplayProgressBar.html

**Comment by talecrafter** [comment]
Added progress bar for multiple files and a few substeps in 4cf3889bba99d6fdf0ea580a69fc1113d93a1a75.
I think it's good enough for most cases so I'm closing this for now.
