### ISSUE TITLE
Error while Path to Aseprite has not been configured

### ISSUE THREAD

**Issue by edwardrowe** [talecrafter/AnimationImporter#14]
Currently the DropButton for importing files is disabled when the application path to Aseprite has not been set up (https://github.com/talecrafter/AnimationImporter/blob/master/Assets/AnimationImporter/Editor/AnimationImporterWindow.cs#L217)

In my opinion, a more elegant solution would be to show an error when they try to drop a file onto the button which would prompt them to set up the path.

An alternative solution (and maybe even better) would be to render the window with a single call to action button when launching the window for the first time. Clicking this button would then prompts them to find the path to Aseprite (as if they pressed the "Select" button in the current Config for Aseprite path).

**Comment by talecrafter** [comment]
Fixed with 8be1984a17f2cd3593df570aae9220573f053412

Not a beautiful single button, but will do for now.
