### ISSUE TITLE
Batch Drag and Drop

### ISSUE THREAD

**Issue by edwardrowe** [talecrafter/AnimationImporter#15]
It would be nice to be able to drag and drop several aseprite files into the importer and have it batch execute the import process on each file. See image for example.

This isn't a high priority at all. Just an idea.

![animationimporter_bulk](https://cloud.githubusercontent.com/assets/398377/22442411/45c86536-e709-11e6-8d9a-272a9818ee78.gif)

**Comment by talecrafter** [comment]
Whoops. Sorry for closing / reopening.
Just wanted to tell you that it's already in the latest commit. Refactored the core a bit so there's now a AnimationImportJob to gather some info for that specific job and Drag & Drop pushes multiple of them.

**Comment by edwardrowe** [comment]
Oh! Sorry for the outdated issue. We'll have to update! Thanks!
