### ISSUE TITLE
Animtion

### ISSUE THREAD

**Issue by AndyGFX** [talecrafter/AnimationImporter#16]
Hi,

 I tried new version and looks like only Sprites (with sprite sheet) folder is created and Animations missing (Anim controller is created). 
I have used Aseprite 1.1.3.

Tried on both drag zones.

Best regards,
AndyGFX

**Comment by talecrafter** [comment]
Could you please send me your file to talecrafter@deathtrash.com along with your Unity Version Number?

**Comment by talecrafter** [comment]
Looked at the file you provided me. You have to assign a Tag for an animation. (Select all frames in the timeline by dragging from 1-12, rightclick -> New Tag.) Then your file works fine.

The Importer should either give a warning in this situation or import the while clip as an "Idle" Animation. Leaving this issue open as a reminder for myself.

**Comment by talecrafter** [comment]
Fixed in c795b8c1aed5108e22de724d293de7d8daefc931
