### ISSUE TITLE
No Error is reported to the user when path to Application is invalid

### ISSUE THREAD

**Issue by edwardrowe** [talecrafter/AnimationImporter#28]
When the user has an improperly configured path to Aseprite, they are unable to drag and drop files into the drop area. This has confused me from time to time, as I couldn't immediately tell whey the file was being rejected.

A fix would be to allow them to drop the file into the area, but show a popup explaining how to fix the problem.

Here's a gif of the described behavior:
![animation-importer-badpath-no-error](https://user-images.githubusercontent.com/398377/46330599-b16fae80-c5e1-11e8-8799-c3972490e7de.gif)

**Comment by talecrafter** [comment]
fix was merged in 1963cbac394047457aec6f3e16e24ffc446fb855
