### ISSUE TITLE
Exception is thrown when opening the editor window in Unity 2018.3

### ISSUE THREAD

**Issue by Slugronaut** [talecrafter/AnimationImporter#32]
The exception "AssetDatabaseUtility CreateDirectoriesInPath expects full Unity path, including 'Assets\". Adding Assets to path." is thrown on line 71 of the file 'AssetDatabaseUtility.cs'. It appears that Unity has changed to nature of its path separator characters to be the standard platform separator Path.DirectorySeparatorChar?

Full exception stack trace:

UnityException: AssetDatabaseUtility CreateDirectoriesInPath expects full Unity path, including 'Assets\". Adding Assets to path.
AnimationImporter.AssetDatabaseUtility.CreateDirectoriesInPath (System.String unityDirectoryPath) (at Assets/3rd Party/AnimationImporter/Editor/Utilities/AssetDatabaseUtility.cs:71)
AnimationImporter.AssetDatabaseUtility.CreateAssetAndDirectories (UnityEngine.Object unityObject, System.String unityFilePath) (at Assets/3rd Party/AnimationImporter/Editor/Utilities/AssetDatabaseUtility.cs:31)
AnimationImporter.ScriptableObjectUtility.LoadOrCreateSaveData[T] (System.String unityPathToFile) (at Assets/3rd Party/AnimationImporter/Editor/Utilities/ScriptableObjectUtility.cs:59)
AnimationImporter.AnimationImporter.LoadOrCreateUserConfig () (at Assets/3rd Party/AnimationImporter/Editor/AnimationImporter.cs:141)
AnimationImporter.AnimationImporterWindow.OnEnable () (at Assets/3rd Party/AnimationImporter/Editor/AnimationImporterWindow.cs:51)
UnityEditor.EditorWindow:GetWindow(Type, Boolean, String)
AnimationImporter.AnimationImporterWindow:ImportAnimationsMenu() (at Assets/3rd Party/AnimationImporter/Editor/AnimationImporterWindow.cs:42)

**Comment by Slugronaut** [comment]
Actually on closer inspection the separator character has remained unchanged. My guess would be that it is due to the directory changes necessitated by the PackageManager. Hard to tell since Unity refuses to let me run the debugger on Wednesdays or Sundays, or when it snows. Or when there is a squirrel outside the window.

**Comment by Slugronaut** [comment]
Nevermind, it definitely is the path separators.  Path.GetDirectoryName(unityFilePath) on line 31 of AssetDatabaseUtility() is changing the directory separators to Windows style.

**Comment by olekmorawski** [comment]
I have the same issue is there a way to fix this?

**Comment by SystemAddict85** [comment]
This seems to fix it for Windows 10.
```
var path = Path.GetDirectoryName(unityFilePath).Replace('\\', UnityDirectorySeparator);
var pathDirectory = path + UnityDirectorySeparator;
CreateDirectoriesInPath(pathDirectory);
```

**Comment by maxpiepenbrink** [comment]
@SystemAddict85 this worked for me, thanks!

**Comment by josephquested** [comment]
@SystemAddict85 thank you very much it also worked for me on windows ten. you should PR this if you haven't already.

**Comment by number304** [comment]
@SystemAddict85 man, you saved my life!

**Comment by talecrafter** [comment]
Finally fixed this. Sorry for taking so long.
Thank you for reporting and posting the issue.
