### ISSUE TITLE
issue when importing pyxelEdit animations

### ISSUE THREAD

**Issue by sglmnaz** [talecrafter/AnimationImporter#38]
the tool splits the sprite just fine but the "pieces" appear to be flipped vertically in their order.
I have to manually open the generated spritesheet, flip the image vertically and save, after doing so the "squares" representing the animation frames are correctly disposed.

![immagine](https://user-images.githubusercontent.com/50869098/64493098-fbdebe00-d27b-11e9-8343-31ac64bc1d70.png)

if you notice in the image, the last row has 13 frames, which should be on the first row, the 4th and the 2nd are inverted too, the middle one is fine. So if i would flip the sprite vertically everything would be fine.

**Comment by talecrafter** [comment]
Was fixed in abc133c0b07076d030bb59db2116c700e34c00e4.
