### ISSUE TITLE
AnimationImporter.cs is giving me an error

### ISSUE THREAD

**Issue by allaze-eroler** [talecrafter/AnimationImporter#47]
i recently tried to use your asset after i downloaded but no matter i try to get a clean install of unity, i always get this message:

>Assets\AnimationImporter\Editor\AnimationImporter.cs(159,21): error CS0234: The type or namespace name 'standardApplicationPath' does not exist in the namespace 'AsepriteImporter' (are you missing an assembly reference?)

even when i deleted the library, it didn't change anything... i also don't understand why my previous unity install worked with it... i use unity 2020.1, 2020.2, 2020.3 and 2021.1 all of them are not working despite from the fact that i upgraded my previous project from 2016.1 to 2021.1 throughout the years without no problem.

**Comment by talecrafter** [comment]
That sounds like the AsepriteImporter file is missing. It should be in the Editor/Aseprite subdirectory of the library. The only other reason this error would occur is if the "using AnimationImporter.Aseprite;" line is missing at the beginning of the AnimationImporter.cs.

I just tested it important the release from here https://github.com/talecrafter/AnimationImporter/releases/tag/1.4 in Unity 2020.3.2f1 and it's working as expected, no error.

**Comment by allaze-eroler** [comment]
thank you for the information! it's been fixed now :)

ps: there is a new version of aseprite with some new features and there will come more soon!
