### ISSUE TITLE
Project maintained?

### ISSUE THREAD

**Issue by GieziJo** [talecrafter/AnimationImporter#48]
Hei

Just wanted to know if there is any plan on continuing maintenance for this project or if we should move to a new fork?
I made a couple of changes which I think could benefit other people (specifying sprite renderer path, retaining per sprite pivot, stuff like that) but if pull requests are not considered I don't think there is much use in sending them here.

Cheers, and again, thanks a lot for this amazing tool.

Best
Giezi

**Comment by talecrafter** [comment]
Well, I didn't lose sight of this project, but I also wasn't able to actively maintain it due to still being overwhelmed with my own project. I'll make the structural changes for this repository now.

Thanks for reminding me.
