### ISSUE TITLE
NonLooping clips could be specified using RegularExpressions

### ISSUE THREAD

**Issue by edwardrowe** [talecrafter/AnimationImporter#9]
Our project is a top down game, so our main character has 8 different facing directions currently. We specify the direction with a suffix. For example, our Idle animation is made up of 8 clips: **Spawn_U**, **Spawn_UR**, **Spawn_R**, etc.

To keep us from having to enter every animation 8 times, we allow users to add regular expressions as our "nonLoopingClipNames". The regex we use right now is:
`Spawn(_U|_UR|_R|_DR|_D|_DL|_L|_UL|\b)` to allow any of the valid suffixes if preceded by an underscore, or to simply allow Idle (which we sometimes use for animations with no blends.)

I also add a word boundary character at the start and end of the supplied names, so that it doesn't break expected behavior for older entries that were expected to match exactly.

The major downside is this may have a performance hit. I'm not exactly sure how slow Regex is, especially when tested against every clip.

**Comment by edwardrowe** [comment]
Another good use case for this would be people who want to include "looping" information in the clip name. Since looping should **ideally** be coming from Aseprite's Tag info, it makes sense to embed it into the clip name.

So for example, you could mark all looping clips with a suffix "_Loop" (e.g. Idle_Loop, Move_Loop). Then you'd simply use a single regex, `^((?!_Loop).)*$`, (which matches all strings that do not contain _Loop) to determine if your clip should loop or not.

**Comment by talecrafter** [comment]
merged in with e550a1caa008071647843ec2ffa4341e9be524fb
